//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode.ConsoleApp.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdventOfCode2015Data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdventOfCode2015Data() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode.ConsoleApp.Data.AdventOfCode2015Data", typeof(AdventOfCode2015Data).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ((((()(()(((((((()))(((()((((()())(())()(((()((((((()((()(()(((()(()((())))()((()()())))))))))()((((((())((()))(((((()(((((((((()()))((()(())()((())((()(()))((()))()))()(((((()(((()()))()())((()((((())()())()((((())()(()(()(((()(())(()(())(((((((())()()(((())(()(()(()(())))(()((((())((()))(((()(()()(((((()()(()(((()(((((())()))()((()(()))()((()((((())((((())(()(((())()()(()()()()()(())((((())((())(()()))()((((())))((((()())()((((())((()())((())(())(((((()((((()(((()((((())(()(((()()))()))((((((()((())()())) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20x3x11
        ///15x27x5
        ///6x29x7
        ///30x15x9
        ///19x29x21
        ///10x4x15
        ///1x26x4
        ///1x5x18
        ///10x15x23
        ///10x14x20
        ///3x5x18
        ///29x23x30
        ///7x4x10
        ///22x24x29
        ///30x1x2
        ///19x2x5
        ///11x9x22
        ///23x15x10
        ///11x11x10
        ///30x28x5
        ///22x5x4
        ///6x26x20
        ///16x12x30
        ///10x20x5
        ///25x14x24
        ///16x17x22
        ///11x28x26
        ///1x11x10
        ///1x24x15
        ///13x17x21
        ///30x3x13
        ///20x25x17
        ///22x12x5
        ///22x20x24
        ///9x2x14
        ///6x18x8
        ///27x28x24
        ///11x17x1
        ///1x4x12
        ///5x20x13
        ///24x23x23
        ///22x1x25
        ///18x19x5
        ///5x23x13
        ///8x16x4
        ///20x21x9
        ///1x7x11
        ///8x30x17
        ///3x30x9
        ///6x16x18
        ///22x25x27
        ///9x20x26
        ///16x21x23
        ///5x24x17
        ///15x17x15
        ///26x15x10
        ///22 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^&gt;&lt;^&gt;&gt;&gt;^&lt;^v&lt;v^^vv^&gt;&lt;&lt;^&lt;&gt;&lt;&lt;vv^&lt;&gt;^&lt;^v&gt;^vv&lt;&gt;v&gt;&lt;vv^^&lt;&gt;&gt;^^^v&lt;&lt;vv&gt;&lt;&lt;^&gt;^&lt;^v&lt;^&gt;^v&gt;&lt;&lt;&lt;v^&lt;v&lt;&lt;&lt;v&lt;&lt;vv&lt;v&lt;^&gt;&lt;^&gt;&gt;&lt;&gt;v&gt;v^&lt;&lt;v^^&lt;^v&lt;&gt;&lt;^&gt;^&lt;&lt;^^^&gt;v&gt;&gt;v^^&lt;v&gt;&gt;^&gt;vv&gt;&lt;v&gt;&gt;^&gt;&gt;v^&gt;^v&gt;^&lt;^^v&gt;^&gt;^^v&lt;v&gt;^^&lt;v&lt;&gt;&gt;v^^v&gt;&lt;^&gt;&lt;^&lt;&lt;&gt;v^&lt;^&lt;^v&lt;v&gt;v^&gt;&gt;&gt;v^v^&gt;^&lt;&gt;^v&lt;^^vv&lt;v&gt;^&gt;^&lt;&gt;^^&lt;vv^&lt;&gt;&lt;&lt;v&lt;^&lt;^^&gt;vv&lt;&gt;^&gt;v&lt;^&gt;^v&gt;v^&gt;^v&lt;&gt;^&gt;&lt;&gt;&gt;&lt;vv&lt;&gt;v^v&lt;&gt;&lt;&gt;v^v&gt;&gt;&gt;&gt;v^^&gt;^&gt;&lt;^^&lt;v&lt;^&gt;&lt;^&lt;v&gt;&gt;^v^v&lt;&gt;v&lt;&lt;&lt;^&lt;&lt;vvvv&lt;&lt;v^vv^&gt;v^^^&lt;^^^&lt;v&gt;&gt;v&lt;^v&gt;&gt;&gt;&gt;&gt;v&lt;^^^^&gt;v&lt;^&lt;&gt;&lt;v&gt;&gt;&gt;&gt;&gt;&lt;v&gt;&gt;v^vvvv^^&lt;v^&lt;&gt;^v&lt;^v^&gt;v&gt;&lt;^&gt;^v&lt;&lt;&gt;&gt;vv^&gt;v&gt;v^^&gt;vv^&lt....
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yzbqklnj.
        /// </summary>
        internal static string _4 {
            get {
                return ResourceManager.GetString("4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sszojmmrrkwuftyv
        ///isaljhemltsdzlum
        ///fujcyucsrxgatisb
        ///qiqqlmcgnhzparyg
        ///oijbmduquhfactbc
        ///jqzuvtggpdqcekgk
        ///zwqadogmpjmmxijf
        ///uilzxjythsqhwndh
        ///gtssqejjknzkkpvw
        ///wrggegukhhatygfi
        ///vhtcgqzerxonhsye
        ///tedlwzdjfppbmtdx
        ///iuvrelxiapllaxbg
        ///feybgiimfthtplui
        ///qxmmcnirvkzfrjwd
        ///vfarmltinsriqxpu
        ///oanqfyqirkraesfq
        ///xilodxfuxphuiiii
        ///yukhnchvjkfwcbiq
        ///bdaibcbzeuxqplop
        ///ivegnnpbiyxqsion
        ///ybahkbzpditgwdgt
        ///dmebdomwabxgtctu
        ///ibtvimgfaeonknoh
        ///jsqraroxudetmfyw
        ///dqdbcwtpintfcvuz
        ///tiyphjunlxddenpj
        ///fgqwjgntxagidhah
        ///nwenhxma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _5 {
            get {
                return ResourceManager.GetString("5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to turn off 660,55 through 986,197
        ///turn off 341,304 through 638,850
        ///turn off 199,133 through 461,193
        ///toggle 322,558 through 977,958
        ///toggle 537,781 through 687,941
        ///turn on 226,196 through 599,390
        ///turn on 240,129 through 703,297
        ///turn on 317,329 through 451,798
        ///turn on 957,736 through 977,890
        ///turn on 263,530 through 559,664
        ///turn on 158,270 through 243,802
        ///toggle 223,39 through 454,511
        ///toggle 544,218 through 979,872
        ///turn on 313,306 through 363,621
        ///toggle 173,401 through 496,407
        ///toggle 333,60 through [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _6 {
            get {
                return ResourceManager.GetString("6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lf AND lq -&gt; ls
        ///iu RSHIFT 1 -&gt; jn
        ///bo OR bu -&gt; bv
        ///gj RSHIFT 1 -&gt; hc
        ///et RSHIFT 2 -&gt; eu
        ///bv AND bx -&gt; by
        ///is OR it -&gt; iu
        ///b OR n -&gt; o
        ///gf OR ge -&gt; gg
        ///NOT kt -&gt; ku
        ///ea AND eb -&gt; ed
        ///kl OR kr -&gt; ks
        ///hi AND hk -&gt; hl
        ///au AND av -&gt; ax
        ///lf RSHIFT 2 -&gt; lg
        ///dd RSHIFT 3 -&gt; df
        ///eu AND fa -&gt; fc
        ///df AND dg -&gt; di
        ///ip LSHIFT 15 -&gt; it
        ///NOT el -&gt; em
        ///et OR fe -&gt; ff
        ///fj LSHIFT 15 -&gt; fn
        ///t OR s -&gt; u
        ///ly OR lz -&gt; ma
        ///ko AND kq -&gt; kr
        ///NOT fx -&gt; fy
        ///et RSHIFT 1 -&gt; fm
        ///eu OR fa -&gt; fb
        ///dd RSHIFT 2 -&gt; de
        ///NOT go -&gt; gp
        ///kb AND kd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _7 {
            get {
                return ResourceManager.GetString("7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;azlgxdbljwygyttzkfwuxv&quot;
        ///&quot;v\xfb\&quot;lgs\&quot;kvjfywmut\x9cr&quot;
        ///&quot;merxdhj&quot;
        ///&quot;dwz&quot;
        ///&quot;d\\gkbqo\\fwukyxab\&quot;u&quot;
        ///&quot;k\xd4cfixejvkicryipucwurq\x7eq&quot;
        ///&quot;nvtidemacj\&quot;hppfopvpr&quot;
        ///&quot;kbngyfvvsdismznhar\\p\&quot;\&quot;gpryt\&quot;jaeh&quot;
        ///&quot;khre\&quot;o\x0elqfrbktzn&quot;
        ///&quot;nugkdmqwdq\x50amallrskmrxoyo&quot;
        ///&quot;jcrkptrsasjp\\\&quot;cwigzynjgspxxv\\vyb&quot;
        ///&quot;ramf\&quot;skhcmenhbpujbqwkltmplxygfcy&quot;
        ///&quot;aqjqgbfqaxga\\fkdcahlfi\&quot;pvods&quot;
        ///&quot;pcrtfb&quot;
        ///&quot;\x83qg\&quot;nwgugfmfpzlrvty\&quot;ryoxm&quot;
        ///&quot;fvhvvokdnl\\eap&quot;
        ///&quot;kugdkrat&quot;
        ///&quot;seuxwc&quot;
        ///&quot;vhioftcosshaqtnz&quot;
        ///&quot;gzkxqrdq\\uko\&quot;mrtst&quot;
        ///&quot;znjcomvy\x16hhsenm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _8 {
            get {
                return ResourceManager.GetString("8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tristram to AlphaCentauri = 34
        ///Tristram to Snowdin = 100
        ///Tristram to Tambi = 63
        ///Tristram to Faerun = 108
        ///Tristram to Norrath = 111
        ///Tristram to Straylight = 89
        ///Tristram to Arbre = 132
        ///AlphaCentauri to Snowdin = 4
        ///AlphaCentauri to Tambi = 79
        ///AlphaCentauri to Faerun = 44
        ///AlphaCentauri to Norrath = 147
        ///AlphaCentauri to Straylight = 133
        ///AlphaCentauri to Arbre = 74
        ///Snowdin to Tambi = 105
        ///Snowdin to Faerun = 95
        ///Snowdin to Norrath = 48
        ///Snowdin to Straylight = 88
        ///Snowdin to Arbre = 7
        ///Tambi to Faeru [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _9 {
            get {
                return ResourceManager.GetString("9", resourceCulture);
            }
        }
    }
}
