//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode.ConsoleApp.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdventOfCode2022Data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdventOfCode2022Data() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode.ConsoleApp.Data.AdventOfCode2022Data", typeof(AdventOfCode2022Data).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18814
        ///
        ///1927
        ///12782
        ///8734
        ///10904
        ///9548
        ///1493
        ///
        ///4576
        ///4235
        ///2617
        ///1012
        ///2088
        ///1325
        ///1249
        ///5173
        ///4893
        ///3295
        ///2376
        ///2714
        ///6210
        ///
        ///6684
        ///5766
        ///3442
        ///4901
        ///4875
        ///4815
        ///5898
        ///2410
        ///5789
        ///4133
        ///3590
        ///1342
        ///
        ///8867
        ///7109
        ///2904
        ///5810
        ///3254
        ///4257
        ///2508
        ///3580
        ///5494
        ///
        ///11885
        ///14638
        ///11891
        ///4244
        ///
        ///11603
        ///17113
        ///
        ///8341
        ///2993
        ///7759
        ///7219
        ///2962
        ///8020
        ///6176
        ///6100
        ///6168
        ///5467
        ///
        ///8884
        ///11521
        ///3912
        ///2993
        ///13471
        ///
        ///3093
        ///4064
        ///9130
        ///7665
        ///10440
        ///6175
        ///7390
        ///10297
        ///
        ///29896
        ///7553
        ///
        ///3709
        ///5876
        ///3564
        ///3824
        ///7695
        ///6789
        ///4295
        ///160 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _1 {
            get {
                return ResourceManager.GetString("1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A X
        ///A Z
        ///A Z
        ///A X
        ///A X
        ///B X
        ///C Y
        ///B X
        ///A Z
        ///A X
        ///A X
        ///A X
        ///A X
        ///B X
        ///A X
        ///B X
        ///A Z
        ///A Z
        ///A X
        ///A X
        ///A Z
        ///A Z
        ///A Z
        ///A X
        ///A Z
        ///A X
        ///C Y
        ///C Z
        ///A X
        ///B X
        ///A X
        ///A X
        ///A X
        ///A Z
        ///B X
        ///A X
        ///B X
        ///C Y
        ///A X
        ///A Z
        ///A Y
        ///A X
        ///A Z
        ///A X
        ///A Z
        ///B X
        ///A X
        ///A Z
        ///B X
        ///A X
        ///A Z
        ///A X
        ///A Z
        ///A Z
        ///A X
        ///B X
        ///B X
        ///B X
        ///B Z
        ///A Z
        ///B Z
        ///A X
        ///A X
        ///A Z
        ///A X
        ///B Z
        ///B Y
        ///A Z
        ///B X
        ///A Y
        ///B X
        ///C X
        ///B Z
        ///B X
        ///C Y
        ///A Z
        ///A X
        ///A X
        ///C Y
        ///B X
        ///A X
        ///A Y
        ///A X
        ///A X
        ///A Y
        ///A Z
        ///C Z
        ///A Z
        ///B X
        ///B X
        ///A X
        ///B X
        ///A X
        ///A X
        ///B Y
        ///B X
        ///A Z
        ///B X
        ///B X
        ///A X
        ///B Z
        ///C Z
        ///A  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _2 {
            get {
                return ResourceManager.GetString("2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGvdqJmJvpNbGRMGQgRsfgfn
        ///WlHTHShlLwSWjFRsncfbcwsgQc
        ///BHtSBHWHSCWLZHlhjTHLLdbNNqNpzpDzNvDvtPmmPp
        ///JJSShnTpDSJJlllfwBNVbMQWwhQhgQtt
        ///cTzrvrHdLwwzttQNWB
        ///qrFqTFvqZvrmsplsjlnDflnZ
        ///mhhhVHvNNddHMwBqQwlWZZtv
        ///fbjzjJllCtWjjrZtjq
        ///CbgcgpPRDJfzVHFFnSnsSDlm
        ///ZqBPqBQnPLmqZsFqhsvFsLZQMfSSMbbWddWbjbJSrgWgJf
        ///NRHnlllcDwwCNClNtttHbNJrSJNfbdWMdfbWgdrJ
        ///cHGlzTptHtCpncHnCpHpRGzDmvVhqLmvLPmPvLqPmzsqqmPB
        ///rCzVtMMbMvCmmvGlclFQFfLpJFJfJpcLHPJL
        ///nDGGwqGqnRTfpHLpRFpLFf
        ///ZNdNTDsWgNZsZBndnGrzrlMrjgrmjVGjvC
        ///MgFZHFTgqFFDZZDTdVdHrzQv [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _3 {
            get {
                return ResourceManager.GetString("3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-2,2-96
        ///17-75,14-75
        ///33-92,93-93
        ///18-18,18-83
        ///14-30,15-30
        ///6-92,6-6
        ///15-16,15-90
        ///32-66,66-77
        ///90-90,89-89
        ///24-71,25-50
        ///31-48,41-42
        ///28-98,28-99
        ///17-44,18-43
        ///5-95,5-45
        ///29-30,30-78
        ///26-71,10-70
        ///62-71,39-71
        ///23-60,24-59
        ///85-93,39-84
        ///3-4,3-58
        ///8-96,8-95
        ///62-79,61-61
        ///15-42,16-41
        ///96-97,68-97
        ///60-72,29-71
        ///22-38,29-37
        ///15-15,15-85
        ///61-85,84-86
        ///22-23,22-40
        ///5-94,35-99
        ///44-98,45-92
        ///12-69,60-67
        ///6-39,7-78
        ///3-28,4-29
        ///26-74,65-72
        ///35-69,34-82
        ///27-97,8-98
        ///3-98,99-99
        ///86-88,9-87
        ///3-18,18-18
        ///12-75,32-74
        ///3 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _4 {
            get {
                return ResourceManager.GetString("4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [P]     [C]         [M]            
        ///[D]     [P] [B]     [V] [S]        
        ///[Q] [V] [R] [V]     [G] [B]        
        ///[R] [W] [G] [J]     [T] [M]     [V]
        ///[V] [Q] [Q] [F] [C] [N] [V]     [W]
        ///[B] [Z] [Z] [H] [L] [P] [L] [J] [N]
        ///[H] [D] [L] [D] [W] [R] [R] [P] [C]
        ///[F] [L] [H] [R] [Z] [J] [J] [D] [D]
        /// 1   2   3   4   5   6   7   8   9 
        ///
        ///move 4 from 9 to 1
        ///move 6 from 3 to 1
        ///move 7 from 4 to 1
        ///move 2 from 8 to 5
        ///move 1 from 9 to 7
        ///move 1 from 8 to 5
        ///move 3 from 6 to 4
        ///move 6 from 1 to 5
        ///move 14 from 1 to [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _5 {
            get {
                return ResourceManager.GetString("5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cbhbmmqnmmqvqfqgqcqmmtvvvdsvscvssmfmhfmhhgdgcclhlnnvmnvmnnwngnqggqlqhhbqbfbvffcpfcfpcpmcppsgssvcvmmdwmwsmwswnwvnvvtgvgfgqqnlltgllpplhpllrnrwrtrzrlrzllpnlpnplnlwnnzfztzcchczctcbbpwpbbfhhqllgrllnnghnnlnznzzlqqmggqbgbjjlnlnjllwlnwnjnbjnnhhcddgmdmqmllfjllddmgmpggtvvqqwmmhcmmjpjdpdqqnhhqbhhscstsvttbwtwdtwwjffvccrwrvvnqqtwwhgwhwthwthhvshsfsjstshthqqdfdhdqhqrqggfffvhffhbbwtbtvtwvvwgvvjjjvtjvvlmlmtmztmthmhttjwwmqqjffhvhqvvrddbsbfbgffmcfffqqfzzgmggzvggbjjmccftcftfnttqqjzjdzdrrgvgsgvvlqvlqqlplnnjccjqcjcgjgfjgjlgjjzhh [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _6 {
            get {
                return ResourceManager.GetString("6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ cd /
        ///$ ls
        ///dir fnsvfbzt
        ///dir hqdssf
        ///dir jwphbz
        ///dir lncqsmj
        ///dir mhqs
        ///dir trwqgzsb
        ///132067 vjw
        ///dir wbsph
        ///$ cd fnsvfbzt
        ///$ ls
        ///62158 sfwnts.hbj
        ///$ cd ..
        ///$ cd hqdssf
        ///$ ls
        ///45626 cvcbmcm
        ///dir dlsmjsbz
        ///dir hqdssf
        ///dir mhqs
        ///dir mtw
        ///dir sfccfsrd
        ///dir shzgg
        ///$ cd dlsmjsbz
        ///$ ls
        ///9205 qcqbgd.lzd
        ///$ cd ..
        ///$ cd hqdssf
        ///$ ls
        ///105963 mhqs.zrn
        ///87909 slwshm.nwr
        ///$ cd ..
        ///$ cd mhqs
        ///$ ls
        ///dir ctfl
        ///45923 jvvl.rcs
        ///dir jzjm
        ///dir lncqsmj
        ///dir mhqs
        ///dir wfbvtfmr
        ///$ cd ctfl
        ///$ ls
        ///dir shzgg
        ///$ cd shzgg
        ///$ ls
        ///18 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _7 {
            get {
                return ResourceManager.GetString("7", resourceCulture);
            }
        }
    }
}
