//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode.ConsoleApp.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdventOfCode2021Data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdventOfCode2021Data() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode.ConsoleApp.Data.AdventOfCode2021Data", typeof(AdventOfCode2021Data).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[{(&lt;({[(([[([()&lt;&gt;][()&lt;&gt;])]][&lt;{[[]&lt;&gt;]}&lt;&lt;[]{}&gt;&gt;&gt;])[({&lt;[{}[]]&lt;{}&lt;&gt;&gt;&gt;&lt;{()[]}[{}[]]&gt;}&lt;&lt;(&lt;&gt;[])[[]{}]&gt;{(&lt;
        ///{{{[[&lt;{&lt;{({({(&lt;&gt;{})}&lt;(()[])([]&lt;&gt;)&gt;)})(&lt;[([{}()]([]{}))[([][])([]&lt;&gt;)]]((&lt;{}&lt;&gt;&gt;[[]{}])({&lt;&gt;()}{()}))&gt;
        ///[(&lt;&lt;[(&lt;[[[&lt;{(([]{})){&lt;{}{}&gt;{()&lt;&gt;}})&gt;&lt;(&lt;[()()][&lt;&gt;]&gt;([[]]))[(([]&lt;&gt;)(&lt;&gt;&lt;&gt;))((&lt;&gt;)({}[]))]&gt;]{&lt;&lt;{{()[]}&lt;[]&lt;&gt;&gt;}
        ///{{({{{([&lt;((&lt;[[&lt;&gt;[]](&lt;&gt;[])]&gt;&lt;&lt;(()&lt;&gt;)&lt;&lt;&gt;&lt;&gt;&gt;&gt;{(()&lt;&gt;)(&lt;&gt;{})}&gt;))&gt;]({(([{{()()}&gt;{{{}{}}{&lt;&gt;&lt;&gt;}}]{({()&lt;&gt;
        ///&lt;&lt;{(&lt;&lt;{&lt;&lt;{([{{(){}}{()()}}{&lt;[]{}&gt;(&lt;&gt;{}))][({&lt;&gt;{}}[[]&lt;&gt;])&lt;{{}{}}{{}()}&gt;])[&lt;&lt;{{}{}}[()[]]&gt;{{
        ///[[&lt;{[&lt;((&lt;[[{{{{ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _10 {
            get {
                return ResourceManager.GetString("10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2478668324
        ///4283474125
        ///1663463374
        ///1738271323
        ///4285744861
        ///3551311515
        ///8574335438
        ///7843525826
        ///1366237577
        ///3554687226.
        /// </summary>
        internal static string _11 {
            get {
                return ResourceManager.GetString("11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start-A
        ///start-b
        ///A-c
        ///A-b
        ///b-d
        ///A-end
        ///b-end.
        /// </summary>
        internal static string _12 {
            get {
                return ResourceManager.GetString("12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forward 4
        ///down 9
        ///forward 6
        ///down 5
        ///up 2
        ///forward 5
        ///forward 7
        ///up 5
        ///down 9
        ///up 6
        ///down 6
        ///down 1
        ///down 1
        ///up 2
        ///down 3
        ///up 3
        ///forward 8
        ///forward 7
        ///down 6
        ///down 7
        ///forward 6
        ///forward 9
        ///forward 7
        ///up 9
        ///down 4
        ///down 6
        ///down 5
        ///down 9
        ///forward 8
        ///down 9
        ///forward 9
        ///forward 4
        ///forward 4
        ///up 3
        ///up 8
        ///down 9
        ///down 8
        ///down 4
        ///forward 5
        ///forward 4
        ///up 6
        ///forward 6
        ///up 3
        ///up 8
        ///up 3
        ///up 4
        ///down 3
        ///down 5
        ///down 5
        ///up 1
        ///forward 9
        ///down 4
        ///forward 6
        ///down 6
        ///up 2
        ///up 9
        ///forward 1
        ///forward 2
        ///forward 7
        ///down 6
        ///u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 010011001001
        ///110101011110
        ///111111000101
        ///100111111001
        ///000000011111
        ///111100100111
        ///011111100000
        ///001001011100
        ///101100111011
        ///010001010100
        ///111011001010
        ///010001100011
        ///110110011011
        ///011011000001
        ///001100101100
        ///001000101100
        ///100000001010
        ///001111110000
        ///100101000000
        ///010000100000
        ///010100110000
        ///110000111101
        ///000001011010
        ///000011011001
        ///011000101110
        ///100011100101
        ///110010010100
        ///001110110101
        ///100011000000
        ///110100111100
        ///100100001111
        ///010110011001
        ///000001111101
        ///100001000010
        ///110010101110
        ///000101001100
        ///10010001 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 93,49,16,88,4,92,23,38,44,98,97,8,5,69,41,70,19,11,29,40,90,43,79,96,68,10,31,35,34,32,0,67,83,33,2,76,24,87,99,77,82,66,12,15,28,59,64,95,91,71,62,22,53,46,39,81,75,86,74,56,50,18,17,73,13,54,60,48,21,51,52,55,85,80,30,36,47,3,26,57,84,25,63,27,37,94,7,45,58,9,78,65,72,6,14,61,20,1,42,89
        ///
        ///83 11 47 61 45
        ///30 74 73 14 66
        ///53 52 10 57 15
        ///64 50 54 28 87
        ///26 85 63 25 86
        ///
        ///72  4 62 30 49
        ///43 93 39 63 25
        ///18 70 44 77 38
        ///84  8 85  5 26
        ///54 50 40 75  2
        ///
        ///70 78 55 26 35
        ///75 44 80 15 34
        ///67 47 53 10 56
        ///73 46 2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _4 {
            get {
                return ResourceManager.GetString("4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 498,436 -&gt; 498,932
        ///173,176 -&gt; 845,848
        ///927,799 -&gt; 927,418
        ///576,67 -&gt; 801,67
        ///908,147 -&gt; 743,147
        ///300,478 -&gt; 300,224
        ///286,979 -&gt; 286,310
        ///230,435 -&gt; 729,934
        ///260,602 -&gt; 260,56
        ///82,686 -&gt; 655,113
        ///460,918 -&gt; 460,224
        ///191,820 -&gt; 454,820
        ///964,483 -&gt; 964,772
        ///395,705 -&gt; 142,705
        ///281,563 -&gt; 134,563
        ///155,509 -&gt; 152,509
        ///754,586 -&gt; 742,586
        ///620,114 -&gt; 620,775
        ///450,476 -&gt; 450,212
        ///135,845 -&gt; 591,845
        ///922,902 -&gt; 110,90
        ///562,71 -&gt; 895,71
        ///843,13 -&gt; 843,620
        ///413,398 -&gt; 486,471
        ///206,601 -&gt; 409,398
        ///854,813 -&gt; 65,813
        ///6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _5 {
            get {
                return ResourceManager.GetString("5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5,1,1,1,3,5,1,1,1,1,5,3,1,1,3,1,1,1,4,1,1,1,1,1,2,4,3,4,1,5,3,4,1,1,5,1,2,1,1,2,1,1,2,1,1,4,2,3,2,1,4,1,1,4,2,1,4,5,5,1,1,1,1,1,2,1,1,1,2,1,5,5,1,1,4,4,5,1,1,1,3,1,5,1,2,1,5,1,4,1,3,2,4,2,1,1,4,1,1,1,1,4,1,1,1,1,1,3,5,4,1,1,3,1,1,1,2,1,1,1,1,5,1,1,1,4,1,4,1,1,1,1,1,2,1,1,5,1,2,1,1,2,1,1,2,4,1,1,5,1,3,4,1,2,4,1,1,1,1,1,4,1,1,4,2,2,1,5,1,4,1,1,5,1,1,5,5,1,1,1,1,1,5,2,1,3,3,1,1,1,3,2,4,5,1,2,1,5,1,4,1,5,1,1,1,1,1,1,4,3,1,1,3,3,1,4,5,1,1,4,1,4,3,4,1,1,1,2,2,1,2,5,1,1,3,5,2,1,1,1,1,1,1,1,4,4,1,5,4,1,1,1,1,1,2,1, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _6 {
            get {
                return ResourceManager.GetString("6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1101,1,29,67,1102,0,1,65,1008,65,35,66,1005,66,28,1,67,65,20,4,0,1001,65,1,65,1106,0,8,99,35,67,101,99,105,32,110,39,101,115,116,32,112,97,115,32,117,110,101,32,105,110,116,99,111,100,101,32,112,114,111,103,114,97,109,10,1247,39,529,198,497,33,1618,2,28,653,764,312,163,62,263,4,243,1277,8,432,324,564,44,56,745,0,534,558,1026,313,482,410,411,63,461,261,561,62,428,42,1806,251,1186,553,241,795,127,1004,94,183,382,194,890,1025,1153,1064,155,278,203,666,1098,678,228,12,530,226,680,476,74,122,136,64,515,630,137,1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _7 {
            get {
                return ResourceManager.GetString("7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bceadfg ebcdaf gdaecf fgcaeb fdbea fcdea cbda begdf afb ba | acfbeg cbfgea gebacf ab
        ///bg dfcba agedcb dfgab agb cafedgb gfdea ceafdg bfgade gbef | befg gafde dafbg cfbadeg
        ///fg befdc afecdbg gbf gfcdab cfge cbdfeg efbdg baegd deafcb | bgf edfbac ebgdf fgb
        ///agbec dbfac gfadeb dgaefcb febcda dcgf bcagd gda fgacdb gd | fgcd fadbce agd dag
        ///bgfad cdfea cfedag bafedc efbda befcadg egbcdf bed be ecab | ecba bed edfab afecgd
        ///dcebaf gf agbcfe agdbcf bfg eafbc gfea gbdce ceafgdb cegfb | faecbd ebcdaf fbg gf
        ///cbgfad  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _8 {
            get {
                return ResourceManager.GetString("8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6587893456954341398543210234567899875421012578932123459998764323569999996432345899989359878998654345
        ///5476894579873210197654328757678910976532323457891012398997653212998798789521256789879498764679795456
        ///5345679989864321349865479869799929987643498598932923987989543209876697654320145679965987653567989767
        ///3235678999965443567976567878999898997654587678949899876878994319965498765421236789764398532479879878
        ///0124789339897764678987878989998767898986798989298798765756989498754349899535456899879987691298568989
        ///12 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _9 {
            get {
                return ResourceManager.GetString("9", resourceCulture);
            }
        }
    }
}
