//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode.ConsoleApp.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdventOfCode2022Data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdventOfCode2022Data() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode.ConsoleApp.Data.AdventOfCode2022Data", typeof(AdventOfCode2022Data).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18814
        ///
        ///1927
        ///12782
        ///8734
        ///10904
        ///9548
        ///1493
        ///
        ///4576
        ///4235
        ///2617
        ///1012
        ///2088
        ///1325
        ///1249
        ///5173
        ///4893
        ///3295
        ///2376
        ///2714
        ///6210
        ///
        ///6684
        ///5766
        ///3442
        ///4901
        ///4875
        ///4815
        ///5898
        ///2410
        ///5789
        ///4133
        ///3590
        ///1342
        ///
        ///8867
        ///7109
        ///2904
        ///5810
        ///3254
        ///4257
        ///2508
        ///3580
        ///5494
        ///
        ///11885
        ///14638
        ///11891
        ///4244
        ///
        ///11603
        ///17113
        ///
        ///8341
        ///2993
        ///7759
        ///7219
        ///2962
        ///8020
        ///6176
        ///6100
        ///6168
        ///5467
        ///
        ///8884
        ///11521
        ///3912
        ///2993
        ///13471
        ///
        ///3093
        ///4064
        ///9130
        ///7665
        ///10440
        ///6175
        ///7390
        ///10297
        ///
        ///29896
        ///7553
        ///
        ///3709
        ///5876
        ///3564
        ///3824
        ///7695
        ///6789
        ///4295
        ///160 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _1 {
            get {
                return ResourceManager.GetString("1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A X
        ///A Z
        ///A Z
        ///A X
        ///A X
        ///B X
        ///C Y
        ///B X
        ///A Z
        ///A X
        ///A X
        ///A X
        ///A X
        ///B X
        ///A X
        ///B X
        ///A Z
        ///A Z
        ///A X
        ///A X
        ///A Z
        ///A Z
        ///A Z
        ///A X
        ///A Z
        ///A X
        ///C Y
        ///C Z
        ///A X
        ///B X
        ///A X
        ///A X
        ///A X
        ///A Z
        ///B X
        ///A X
        ///B X
        ///C Y
        ///A X
        ///A Z
        ///A Y
        ///A X
        ///A Z
        ///A X
        ///A Z
        ///B X
        ///A X
        ///A Z
        ///B X
        ///A X
        ///A Z
        ///A X
        ///A Z
        ///A Z
        ///A X
        ///B X
        ///B X
        ///B X
        ///B Z
        ///A Z
        ///B Z
        ///A X
        ///A X
        ///A Z
        ///A X
        ///B Z
        ///B Y
        ///A Z
        ///B X
        ///A Y
        ///B X
        ///C X
        ///B Z
        ///B X
        ///C Y
        ///A Z
        ///A X
        ///A X
        ///C Y
        ///B X
        ///A X
        ///A Y
        ///A X
        ///A X
        ///A Y
        ///A Z
        ///C Z
        ///A Z
        ///B X
        ///B X
        ///A X
        ///B X
        ///A X
        ///A X
        ///B Y
        ///B X
        ///A Z
        ///B X
        ///B X
        ///A X
        ///B Z
        ///C Z
        ///A  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _2 {
            get {
                return ResourceManager.GetString("2", resourceCulture);
            }
        }
    }
}
